# Generated by Django 2.2.5 on 2020-03-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200304_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_user_value',
        ),
    ]
