# Generated by Django 2.2.10 on 2020-03-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_board_is_user_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='value',
            field=models.CharField(max_length=300),
        ),
    ]
