# Generated by Django 2.2.5 on 2020-03-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('value', models.SmallIntegerField()),
                ('is_user_value', models.BinaryField(default=False)),
            ],
        ),
    ]
