# Generated by Django 2.2.5 on 2020-03-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20200310_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile2',
            name='portfolio_site',
        ),
    ]
