# Generated by Django 2.2.5 on 2020-03-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_userprofile2_portfolio_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile1',
        ),
        migrations.DeleteModel(
            name='UserProfile2',
        ),
    ]
